title: International Committee on Taxonomy of Viruses
description: We created this website to share information and data on the ICTV Virus Computational Taxonomy Challenge
theme: jekyll-theme-minimal
logo: /assets/img/logo_new.png
# favicon: /assets/img/favicon.ico
