title: ICTV Taxonomy Challenge
description: We created this website to share information and data on the upcoming ICTV Taxonomy Challenge
logo: /assets/img/logo_ictv_tc.png
theme: jekyll-theme-minimal
